version: 2

models:
  - name: dim_games
    description: "게임과 차원 데이터를 조합한 마트 테이블"
    columns:
      - name: game_id
        description: "게임 고유 ID"
        tests:
          - not_null
          - unique
      - name: game_name
        description: "게임 이름"
        tests:
          - not_null
      - name: game_summary
        description: "게임 요약 정보"
      - name: platform_names
        description: "플랫폼 이름"
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              arguments:
                column_type: "VARCHAR[]"
      - name: genre_names
        description: "장르 이름"
      - name: game_mode_names
        description: "게임 모드 이름"
      - name: theme_names
        description: "테마 이름"
      - name: player_perspectives
        description: "플레이어 시점"
      - name: hypes
        description: "게임에 대한 기대감(Hype)"
        tests:
          - not_null:
              config:
                severity: warn
      - name: aggregated_rating
        description: "외부 비평가 평균 평점 (0-100)"
      - name: aggregated_rating_count
        description: "평가 참여 수"
