name: "transform"
version: "1.0.0"

profile: "transform"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  transform:
    staging:
      +materialized: "{{ 'ephemeral' if target.name == 'prod_s3' else 'view' }}"
      +schema: staging

      bridge:
        +materialized: "{{ 'table' if target.name == 'prod_s3' else 'view' }}"

    marts:
      +materialized: "{{ 'table' if target.name == 'prod_s3' else 'view' }}"
      +schema: marts
